config/routes.rb
Rails.application.routes.draw do
  
  resources :students
  
    root 'database#index'
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def hello 
    render text: "hello, world!"   
  end 

end

app/controllers/database_controller.rb
class DatabaseController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
  end
  
  def create

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/database_helper.rb
module DatabaseHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/database/index.html.erb
<h1>Student Database</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>STUDENTS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= form_for :Student, url: students_path do |f| %>
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
  </p>
 
  <p>
    <%= f.label :Gender %><br>
    <%= f.text_field :Gender %>
  </p>
 
  <p>
    <%= f.submit 'Update Student' %>
  </p>
<% end %>